echo '___                                   '
echo ' |   _      _ |_      _   _ |_ |_     '
echo ' |  |  |_| _) |_ \)/ (_) |  |_ | ) \/ '
echo '                                   /  '
echo ' __                                   '
echo '(_      _ |_  _  _   _                '
echo '__) \/ _) |_ (- ||| _)                '
echo '    /                                 '
echo 'Hello, welcome to the seL4/CAmkES/L4v docker build environment'
